config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :info_texts
  resources :notices
  resources :courses
  resources :covers
  resources :comments

  get '/list_courses/:id', to: 'courses#list_courses'
  get '/dashboard', to: 'admin#dashboard'
  get '/login', to: 'admin#login'

  #get '/live-the-experience', to: 'videos#index'
  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/notice.rb
class Notice < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates :title, :link, presence: true
  validates :title, length: { in: 15..70, wrong_length: "El titulo de la noticia debe tener entre 15 a 70 caracteres"  }
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]
  before_action :check_credentials
  layout 'dashboard'

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:title, :link, :image)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= form_for(notice, local: true, html: { multipart: true }) do |form| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :titulo %>
    <%= form.text_field :title, id: :notice_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :enlace %>
    <%= form.text_field :link, id: :notice_link, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Aceptar", class: "btn btn-success" %>
    <%= link_to "Atrás", notices_url, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<section id="page-content">
  <div class="container">
    <h1>Editar noticia</h1>

    <%= render 'form', notice: @notice %>

  </div>
</section>

app/views/notices/index.html.erb
<section id="page-content">
  <div class="container">

    <h1>Noticias</h1>
    
    <%= link_to 'Agregar noticia', new_notice_path, class: "btn btn-primary" %>
    <%= link_to 'Atrás', dashboard_path, class: "btn btn-danger" %>
    
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Titulo</th>
            <th>Enlace</th>
            <th colspan="3"></th>
          </tr>
        </thead>
  
        <tbody>
          <% @notices.each do |notice| %>
            <tr>
              <td><%= notice.title %></td>
              <td><%= notice.link %></td>
              <td><%= link_to 'Ver noticia', notice %></td>
              <td><%= link_to 'Editar noticia', edit_notice_path(notice) %></td>
              <td><%= link_to 'Eliminar noticia', notice, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <br>

    
  </div>
</section>

app/views/notices/new.html.erb
<section id="page-content">
  <div class="container">
    <h1>Nueva noticia</h1>

    <%= render 'form', notice: @notice %>

  </div>
</section>

app/views/notices/show.html.erb
<section id="page-content">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Titulo:</strong>
      <%= @notice.title %>
    </p>

    <p>
      <strong>Enlace:</strong>
      <%= @notice.link %>
    </p>

    <%= link_to 'Editar noticia', edit_notice_path(@notice) %> |
    <%= link_to 'Atras', notices_path %>
  </div>
</section>