config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :info_texts
  resources :notices
  resources :courses
  resources :covers
  resources :comments

  get '/list_courses/:id', to: 'courses#list_courses'
  get '/dashboard', to: 'admin#dashboard'
  get '/login', to: 'admin#login'

  #get '/live-the-experience', to: 'videos#index'
  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/comment.rb
class Comment < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates :name, :content, presence: true
  validates :name, length: { in: 6..25, wrong_length: "El nombre del comentario debe tener entre 6 a 25 caracteres"}
  validates :content, length: { in: 50..500, wrong_length: "El contenido del comentario debe tener entre 50 a 500 caracteres"}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :check_credentials

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :content, :photo)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment, local: true, html: { multipart: true }) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :name, id: :comment_name %>
  </div>

  <div class="field">
    <%= form.label :contenido %>
    <%= form.text_area :content, id: :comment_content %>
  </div>

  <div class="field">
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit :enviar %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<section id="page-content">
  <div class="container">
    <h1>Editar Comentario</h1>

    <%= render 'form', comment: @comment %>

    <%= link_to 'Ver comentario', @comment %> |
    <%= link_to 'Atras', comments_path %>
  </div>
</section>

app/views/comments/index.html.erb
<section id="page-content">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <h1>Comentarios</h1>

    <table>
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Contenido</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td><%= comment.name %></td>
            <td><%= comment.content %></td>
            <td><%= link_to 'Ver comentario', comment %></td>
            <td><%= link_to 'Editar comentario', edit_comment_path(comment) %></td>
            <td><%= link_to 'Eliminar comentario', comment, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <% if @comments.count < 3 %>
      <%= link_to 'Agregar comentario', new_comment_path %>
    <% end %>
    <%= link_to 'Atras', dashboard_path %>
  </div>
</section>

app/views/comments/new.html.erb
<section id="page-content">
  <div class="container">
    <h1>Nuevo comentario</h1>

    <%= render 'form', comment: @comment %>

    <%= link_to 'Atras', comments_path %>
  </div>
</section>

app/views/comments/show.html.erb
<section id="page-content">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Nombre:</strong>
      <%= @comment.name %>
    </p>

    <p>
      <strong>Contenido:</strong>
      <%= @comment.content %>
    </p>

    <%= link_to 'Editar comentario', edit_comment_path(@comment) %> |
    <%= link_to 'Atras', comments_path %>
  </div>
</section>