config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :info_texts
  resources :notices
  resources :courses
  resources :covers
  resources :comments

  get '/list_courses/:id', to: 'courses#list_courses'
  get '/dashboard', to: 'admin#dashboard'
  get '/login', to: 'admin#login'

  #get '/live-the-experience', to: 'videos#index'
  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/info_text.rb
class InfoText < ApplicationRecord
  validates :title, uniqueness: true
  validates :content, :title, presence: true
  validates :content, length: { in: 50..500, wrong_length: "El contenido del texto informativo
    debe tener entre 50 a 500 caracteres"  }
end

app/controllers/info_texts_controller.rb
class InfoTextsController < ApplicationController
  before_action :set_info_text, only: [:show, :edit, :update, :destroy]
  before_action :check_credentials
  layout 'dashboard'
  # GET /info_texts
  # GET /info_texts.json
  def index
    @info_texts = InfoText.all
  end

  # GET /info_texts/1
  # GET /info_texts/1.json
  def show
  end

  # GET /info_texts/new
  def new
    @info_text = InfoText.new
  end

  # GET /info_texts/1/edit
  def edit
  end

  # POST /info_texts
  # POST /info_texts.json
  def create
    @info_text = InfoText.new(info_text_params)

    respond_to do |format|
      if @info_text.save
        format.html { redirect_to @info_text, notice: 'Info text was successfully created.' }
        format.json { render :show, status: :created, location: @info_text }
      else
        format.html { render :new }
        format.json { render json: @info_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /info_texts/1
  # PATCH/PUT /info_texts/1.json
  def update
    respond_to do |format|
      if @info_text.update(info_text_params)
        format.html { redirect_to @info_text, notice: 'Info text was successfully updated.' }
        format.json { render :show, status: :ok, location: @info_text }
      else
        format.html { render :edit }
        format.json { render json: @info_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /info_texts/1
  # DELETE /info_texts/1.json
  def destroy
    @info_text.destroy
    respond_to do |format|
      format.html { redirect_to info_texts_url, notice: 'Info text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info_text
      @info_text = InfoText.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_text_params
      params.require(:info_text).permit(:title, :content)
    end
end

app/helpers/info_texts_helper.rb
module InfoTextsHelper
end

app/views/info_texts/_form.html.erb
<%= form_for(info_text, local: true) do |form| %>
  <% if info_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(info_text.errors.count, "error") %> prohibited this info_text from being saved:</h2>

      <ul>
      <% info_text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :titulo %>
    <%= form.select :title, options_for_select([ "Quienes somos", "Ofertas Academicas", "Vive la experiencia" ], "Quienes somos"), id: :info_text_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :contenido %>
    <%= form.text_area :content, id: :info_text_content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Aceptar", class: "btn btn-success" %>
    <%= link_to "Atrás", info_texts_url, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/info_texts/edit.html.erb
<section id="page-content">
  <div class="container">
    <h1>Editar texto informativo</h1>

    <%= render 'form', info_text: @info_text %>

  </div>
</section>

app/views/info_texts/index.html.erb
<section id="page-content">
  <div class="container">

    <h1>Textos</h1>
    <% if @info_texts.count < 3 %>
      <%= link_to 'Agregar texto informativo', new_info_text_path, class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'Atras', dashboard_path, class: "btn btn-danger" %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Titulo</th>
            <th>Contenido</th>
            <th colspan="3"></th>
          </tr>
        </thead>
  
        <tbody>
          <% @info_texts.each do |info_text| %>
            <tr>
              <td><%= info_text.title %></td>
              <td><%= info_text.content %></td>
              <td><%= link_to 'Ver texto', info_text %></td>
              <td><%= link_to 'Editar texto', edit_info_text_path(info_text) %></td>
              <td><%= link_to 'Eliminar texto', info_text, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
      
    <br>
  </div>
</section>

app/views/info_texts/new.html.erb
<section id="page-content">
  <div class="container">
    <h1>Nuevo texto informativo</h1>

    <%= render 'form', info_text: @info_text %>

  </div>
</section>

app/views/info_texts/show.html.erb
<section id="page-content">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Titulo:</strong>
      <%= @info_text.title %>
    </p>

    <p>
      <strong>Contenido:</strong>
      <%= @info_text.content %>
    </p>

    <%= link_to 'Editar texto', edit_info_text_path(@info_text) %> |
    <%= link_to 'Atras', info_texts_path %>
  </div>
</section>