config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :info_texts
  resources :notices
  resources :courses
  resources :covers
  resources :comments

  get '/list_courses/:id', to: 'courses#list_courses'
  get '/dashboard', to: 'admin#dashboard'
  get '/login', to: 'admin#login'

  #get '/live-the-experience', to: 'videos#index'
  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :contrasena %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label "confirmar contrasena" %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit :enviar %>
  </div>
<% end %>

app/views/users/edit.html.erb
<section id="page-content">
  <div class="container">
    <h1>Editar usuario</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Ver', @user %> |
    <%= link_to 'Atras', users_path %>
  </div>
</section>

app/views/users/index.html.erb
<section id="page-content">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <h1>Usuarios</h1>

    <table>
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Email</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.status %></td>
            <td><%= link_to 'Ver usuario', user %></td>
            <td><%= link_to 'Editar usuario', edit_user_path(user) %></td>
            <% if user.status != "administrador" %>
              <td><%= link_to 'Eliminar usuario', user, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Agregar un nuevo usuario', new_user_path %>
    <%= link_to 'Atras', dashboard_path %>
  </div>
</section>

app/views/users/main.html.erb
<section id="page-content">
  <div class="container">
    <h1>Bienvenido, que deseas modificar</h1>
    <ul>
      <% if current_user.status == "administrador" %>
        <li><%= link_to 'usuarios', users_path %></li>
      <% end %>
      <li><%= link_to 'noticias', notices_path %></li>
      <li><%= link_to 'textos informativos', info_texts_path %></li>
      <li><%= link_to 'portadas', covers_path %></li>
      <li><%= link_to 'cursos', courses_path %></li>
      <li><%= link_to 'comentarios', comments_path %></li>
    </ul>
  </div>
</section>

app/views/users/new.html.erb
<section id="page-content">
  <div class="container">
    <h1>Crear nuevo usuario</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Atras', users_path %>
  </div>
</section>

app/views/users/show.html.erb
<section id="page-content">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Nombre:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @user.status %>
    </p>

    <%= link_to 'Editar usuario', edit_user_path(@user) %> |
    <%= link_to 'Atras', users_path %>
  </div>
</section>